development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: bagels_test
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: sample_postgres_production
#   pool: 5
#   username: sample_postgres
#   password: